export const API_SERVER = 'https://swapi.co/api';

export const PLANETS_STARTS = 'PLANETS_STARTS';
export const PLANETS_ADDED = 'PLANETS_ADDED';
export const PLANETS_SUCCESS = 'PLANETS_SUCCESS';
export const PLANETS_FAILURE = 'PLANETS_FAILURE';

export const FILMS_STARTS = 'FILMS_STARTS';
export const FILMS_ADDED = 'FILMS_ADDED';
export const FILMS_SUCCESS = 'FILMS_SUCCESS';
export const FILMS_FAILURE = 'FILMS_FAILURE';

export const PEOPLES_STARTS = 'PEOPLES_STARTS';
export const PEOPLES_ADDED = 'PEOPLES_ADDED';
export const PEOPLES_SUCCESS = 'PEOPLES_SUCCESS';
export const PEOPLES_FAILURE = 'PEOPLES_FAILURE';

export const STARSHIPS_STARTS = 'STARSHIPS_STARTS';
export const STARSHIPS_ADDED = 'STARSHIPS_ADDED';
export const STARSHIPS_SUCCESS = 'STARSHIPS_SUCCESS';
export const STARSHIPS_FAILURE = 'STARSHIPS_FAILURE';

export const SPECIES_STARTS = 'SPECIES_STARTS';
export const SPECIES_ADDED = 'SPECIES_ADDED';
export const SPECIES_SUCCESS = 'SPECIES_SUCCESS';
export const SPECIES_FAILURE = 'SPECIES_FAILURE';

export const VECHICLES_STARTS = 'VECHICLES_STARTS';
export const VECHICLES_ADDED = 'VECHICLES_ADDED';
export const VECHICLES_SUCCESS = 'VECHICLESS_SUCCESS';
export const VECHICLES_FAILURE = 'VECHICLES_FAILURE';