export const API_SERVER = 'https://swapi.co/api';

export const PLANETS_STARTS = 'PLANETS_STARTS';
export const PLANETS_NEXT_SUCCESS = 'PLANETS_NEXT_SUCCESS';
export const PLANETS_SUCCESS = 'PLANETS_SUCCESS';
export const PLANETS_FAILURE = 'PLANETS_FAILURE';

export const FILMS_STARTS = 'FILMS_STARTS';
export const FILMS_NEXT_SUCCESS = 'FILMS_NEXT_SUCCESS';
export const FILMS_SUCCESS = 'FILMS_SUCCESS';
export const FILMS_FAILURE = 'FILMS_FAILURE';

export const PEOPLES_STARTS = 'PEOPLES_STARTS';
export const PEOPLES_NEXT_SUCCESS = 'PEOPLES_NEXT_SUCCESS';
export const PEOPLES_SUCCESS = 'PEOPLES_SUCCESS';
export const PEOPLES_FAILURE = 'PEOPLES_FAILURE';

export const STARSHIPS_STARTS = 'STARSHIPS_STARTS';
export const STARSHIPS_NEXT_SUCCESS = 'STARSHIPS_NEXT_SUCCESS';
export const STARSHIPS_SUCCESS = 'STARSHIPS_SUCCESS';
export const STARSHIPS_FAILURE = 'STARSHIPS_FAILURE';

export const SPECIES_STARTS = 'SPECIES_STARTS';
export const SPECIES_NEXT_SUCCESS = 'SPECIES_NEXT_SUCCESS';
export const SPECIES_SUCCESS = 'SPECIES_SUCCESS';
export const SPECIES_FAILURE = 'SPECIES_FAILURE';

export const VECHICLES_STARTS = 'VECHICLES_STARTS';
export const VECHICLES_NEXT_SUCCESS = 'VECHICLES_NEXT_SUCCESS';
export const VECHICLES_SUCCESS = 'VECHICLESS_SUCCESS';
export const VECHICLES_FAILURE = 'VECHICLES_FAILURE';